name = "family-quicktree"
compatibility_date = "2024-01-01"

[build]
command = "bun run build"
cwd = "."

pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "TREES"
id = "4465fa8a51ea458a9dd3085c6e8116cc"
